const $=s=>document.querySelector(s);let me=null;async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});const d=await r.json();if(!r.ok)throw Error(d.error||'Fout');return d}function esc(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function fmtDate(s){return new Date(s+'T12:00:00Z').toLocaleDateString('nl-BE',{day:'2-digit',month:'2-digit',year:'numeric'})}
async function loadNames(){const d=await api('/api/public-players');$('#playerNames').innerHTML=d.players.map(p=>`<option value="${esc(p.name)}">`).join('')}
async function refreshBoard(){const d=await api('/api/leaderboard');$('#weekLabel').textContent=d.label;$('#board').innerHTML=d.rows.length?d.rows.map((r,i)=>`<tr><td>${i<3?['🥇','🥈','🥉'][i]:i+1}</td><td><strong>${esc(r.name)}</strong></td><td class="best">${r.best}</td><td>${r.throws}</td></tr>`).join(''):'<tr><td colspan="4" class="empty">Nog geen worpen deze week. Wees de eerste!</td></tr>';if(d.rows[0]){$('#winnerName').textContent=d.rows[0].name;$('#winnerScore').textContent=d.rows[0].best;$('#winnerRule').textContent=`Beste worp · ${d.rows[0].throws} ${d.rows[0].throws===1?'worp':'worpen'} deze week`}else{$('#winnerName').textContent='Nog niemand bovenaan';$('#winnerScore').textContent='—';$('#winnerRule').textContent='De eerste worp van de week kan alles veranderen.'}}
function showApp(){$('#nameView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#playerName').textContent=me.name}
function setSubmitted(t){if(t.submitted){$('#scoreMsg').innerHTML=`✓ Je hebt vandaag al <strong>${t.score}</strong> gegooid. Tot morgen!`;$(' #score')?.removeAttribute('required');$('#score').disabled=true;$('#scoreForm button').disabled=true}else{$('#scoreMsg').textContent='';$('#score').disabled=false;$('#scoreForm button').disabled=false}}
async function loadStats(){const d=await api('/api/my-stats');const w=d.week,a=d.allTime;$('#myStats').innerHTML=`<div class="stats-grid"><div><span>Deze week</span><strong>${w.best??'—'}</strong><small>beste worp · ${w.throws} ${w.throws==1?'worp':'worpen'}</small></div><div><span>Gemiddelde</span><strong>${a.throws?Number(a.average).toFixed(1):'—'}</strong><small>over ${a.throws} ${a.throws==1?'worp':'worpen'} ooit</small></div></div>`;$('#history').innerHTML=d.history.length?`<div class="table-wrap"><table><thead><tr><th>Datum</th><th>Worp</th><th>Week</th></tr></thead><tbody>${d.history.map(x=>`<tr><td>${fmtDate(x.throw_date)}</td><td class="best">${x.score}</td><td>vanaf ${fmtDate(x.week_start)}</td></tr>`).join('')}</tbody></table></div>`:'<p>Nog geen historische worpen.</p>'}
$('#nameForm').addEventListener('submit',async e=>{e.preventDefault();try{const d=await api('/api/select-player',{method:'POST',body:JSON.stringify({name:$('#name').value})});me=d.player;showApp();setSubmitted(await api('/api/today'));await loadStats();await refreshBoard();document.getElementById('meedoen').scrollIntoView({behavior:'smooth'})}catch(x){$('#nameMsg').textContent=x.message}});
$('#scoreForm').addEventListener('submit',async e=>{e.preventDefault();try{const d=await api('/api/scores',{method:'POST',body:JSON.stringify({score:$('#score').value})});$('#scoreMsg').innerHTML=`✓ <strong>${d.score}</strong> is binnen! Tot morgen.`;setSubmitted({submitted:true,score:d.score});await loadStats();await refreshBoard()}catch(x){$('#scoreMsg').textContent=x.message}});
$('#logout').addEventListener('click',async()=>{await api('/api/logout',{method:'POST'});location.reload()});
(async()=>{try{await loadNames();const d=await api('/api/me');if(d.player){me=d.player;showApp();setSubmitted(await api('/api/today'));await loadStats()};await refreshBoard()}catch(e){console.error(e)}})();
