const $=s=>document.querySelector(s);let me=null;
async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});const d=await r.json();if(!r.ok)throw Error(d.error||'Er ging iets mis.');return d}
function esc(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function loadNames(){const d=await api('/api/public-players').catch(()=>null);if(d){$('#name').innerHTML='<option value="">Kies je naam…</option>'+d.players.map(p=>`<option>${esc(p.name)}</option>`).join('')}}
async function refreshBoard(){const d=await api('/api/leaderboard');$('#weekLabel').textContent=d.label;$('#board').innerHTML=d.rows.length?d.rows.map((r,i)=>`<tr class="${i===0?'top':''}"><td>${i===0?'🏆':i+1}</td><td><strong>${esc(r.name)}</strong></td><td class="best">${r.best}</td><td>${r.throws}</td></tr>`).join(''):'<tr><td colspan="4" class="empty">Nog geen worpen deze week. Wees de eerste!</td></tr>';
 if(d.rows[0]){$('#winnerName').textContent=d.rows[0].name;$('#winnerScore').textContent=d.rows[0].best;$('#winnerRule').textContent=`Beste worp · ${d.rows[0].throws} ${d.rows[0].throws===1?'worp':'worpen'} deze week`}
 else{$('#winnerName').textContent='Nog niemand bovenaan';$('#winnerScore').textContent='—'}
 if(me){const mine=d.rows.find(r=>r.id===me.id);$('#myStats').innerHTML=mine?`<div class="big-stat">${mine.best}</div><strong>Beste worp</strong><span>${mine.throws} ${mine.throws===1?'worp':'worpen'} deze week</span>`:`<div class="big-stat muted-number">—</div><strong>Nog geen worp</strong><span>Doe vandaag mee!</span>`}}
async function init(){await loadNames();const d=await api('/api/me');if(d.player){me=d.player;showApp();const t=await api('/api/today');setSubmitted(t)}await refreshBoard()}
function showApp(){$('#nameView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#playerName').textContent=me.name}
function setSubmitted(t){if(t.submitted){$('#scoreMsg').innerHTML=`✓ Je hebt vandaag al <strong>${t.score}</strong> gegooid. Tot morgen!`;$('#score').disabled=true;$('#scoreForm button').disabled=true}else{$('#score').disabled=false;$('#scoreForm button').disabled=false}}
$('#nameForm').addEventListener('submit',async e=>{e.preventDefault();try{const d=await api('/api/select-player',{method:'POST',body:JSON.stringify({name:$('#name').value,code:$('#code').value})});me=d.player;showApp();setSubmitted(await api('/api/today'));await refreshBoard();document.getElementById('meedoen').scrollIntoView({behavior:'smooth'})}catch(x){$('#nameMsg').textContent=x.message}});
$('#scoreForm').addEventListener('submit',async e=>{e.preventDefault();try{const d=await api('/api/scores',{method:'POST',body:JSON.stringify({score:$('#score').value})});$('#scoreMsg').innerHTML=`✓ <strong>${d.score}</strong> is binnen! Tot morgen.`;setSubmitted({submitted:true,score:d.score});await refreshBoard()}catch(x){$('#scoreMsg').textContent=x.message}});
$('#logout').addEventListener('click',async()=>{await api('/api/logout',{method:'POST'});location.reload()});init();
